---
- name: Pull registry image
  docker_image:
    name: registry
    source: pull

- name: Reload daemon
  command: systemctl daemon-reload
  become: yes

- name: Restart docker
  command: systemctl restart docker
  become: yes

- name: Run registry container
  command: docker run -dit -p 5000:5000 --restart=always --name registry registry
  ignore_errors: yes
  