- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge & Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: "{{ item }}"
    option: enabled
    value: "0"
  with_items:
    - docker-ce-test
    - docker-ce-edge

- name: Install Docker
  package:
    name: docker-ce
    state: latest

- name: Install Epel-Release
  yum: 
    name: epel-release
    state: latest

- name: Install Python-Pip
  yum: 
    name: python-pip
    state: latest
  
- name: Install Docker-Py
  command: pip install docker-py
